import pygame as pg

pg.font.init()

# -- Sizing and Configuration --
WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
BG_COLOR = (200, 200, 200)

BOARD_DIMENSION = 480
BOARD_SIZE = (BOARD_DIMENSION, BOARD_DIMENSION)
BOARD_POS = (WINDOW_WIDTH // 2, WINDOW_HEIGHT // 2)
BOARD_COLOR = (160, 160, 160)

TILE_COLOR = (180, 180, 180)

FONT = pg.font.SysFont('Arial Black', 30)